/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conexao;

import DAO.BebidaDAO;
import DAO.ComidaDAO;
import DAO.SobremesaDAO;
import beans.Bebida;
import beans.Comida;
import beans.Sobremesa;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class EditarItens extends javax.swing.JFrame {

    /**
     * Creates new form EditarItens
     */
    public EditarItens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtConsultaIDitem = new javax.swing.JTextField();
        btnConsultarItem = new javax.swing.JButton();
        lblMostrarID = new javax.swing.JLabel();
        txtMostrarIDitem = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescricao = new javax.swing.JTextArea();
        lblDescricao = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        lblTipoItem = new javax.swing.JLabel();
        cmbTipoItem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição de Itens");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblID.setText("ID:");

        btnConsultarItem.setBackground(new java.awt.Color(242, 255, 255));
        btnConsultarItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultarItem.setText("Consultar");
        btnConsultarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarItemActionPerformed(evt);
            }
        });

        lblMostrarID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMostrarID.setText("ID:");

        txtMostrarIDitem.setEditable(false);
        txtMostrarIDitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostrarIDitemActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(102, 255, 102));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Valor:");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Informe o ID do Item para consultá-lo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Informações do Item:");

        txaDescricao.setColumns(20);
        txaDescricao.setRows(5);
        jScrollPane1.setViewportView(txaDescricao);

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(153, 153, 153));
        lblDescricao.setText("Descrição");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponivel", "Indisponivel" }));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(153, 153, 153));
        lblStatus.setText("Estado");

        lblTipoItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipoItem.setText("Item:");

        cmbTipoItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTipoItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Hamburguer", "Sobremesa", " " }));
        cmbTipoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoItemActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Informe o tipo de Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTipoItem)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addComponent(lblID)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtConsultaIDitem, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMostrarID)
                                .addGap(18, 18, 18)
                                .addComponent(txtMostrarIDitem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus))
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultaIDitem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoItem)
                            .addComponent(cmbTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMostrarID)
                            .addComponent(txtMostrarIDitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnAtualizar)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnConsultarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarItemActionPerformed

        if(cmbTipoItem.getSelectedIndex() == 0){
            BebidaDAO bDAO = new BebidaDAO();
            int id = Integer.parseInt(txtConsultaIDitem.getText());
            Bebida b = bDAO.consulta(id);
            
            if(b == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Bebida não encontrada");
        }
         else{
            txtMostrarIDitem.setText(String.valueOf(b.getId()));
            txtNome.setText(b.getNome());
            txtValor.setText(String.valueOf(b.getValor()));
            txtQuantidade.setText(String.valueOf(b.getQuantidade()));
            cmbEstado.setSelectedItem(b.getEstado());
            }
        }
        else if(cmbTipoItem.getSelectedIndex() == 1){
            ComidaDAO cDAO = new ComidaDAO();
            int id = Integer.parseInt(txtConsultaIDitem.getText());
            Comida c = cDAO.consulta(id);
            
            if(c == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Comida não encontrada");
            }
         else{
            txtMostrarIDitem.setText(String.valueOf(c.getId()));
            txtNome.setText(c.getNome());
            txtValor.setText(String.valueOf(c.getValor()));
            txtQuantidade.setText(String.valueOf(c.getQuantidade()));
            txaDescricao.setText(c.getDescricao());
            cmbEstado.setSelectedItem(c.getEstado());
            }
        }
        else if(cmbTipoItem.getSelectedIndex() == 2){
            SobremesaDAO sDAO = new SobremesaDAO();
            int id = Integer.parseInt(txtConsultaIDitem.getText());
            Sobremesa s = sDAO.consulta(id);
            
            if(s == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Sobremesa não encontrada");
            }
         else{
            txtMostrarIDitem.setText(String.valueOf(s.getId()));
            txtNome.setText(s.getNome());
            txtValor.setText(String.valueOf(s.getValor()));
            txtQuantidade.setText(String.valueOf(s.getQuantidade()));
            txaDescricao.setText(s.getDescricao());
            cmbEstado.setSelectedItem(s.getEstado());
            }
        }
        
        
        
        

    }//GEN-LAST:event_btnConsultarItemActionPerformed

    private void txtMostrarIDitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostrarIDitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMostrarIDitemActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

          
        
        if (cmbTipoItem.getSelectedIndex() == 0){
            Bebida b = new Bebida();
            b.setId(Integer.parseInt(txtMostrarIDitem.getText()));
            b.setNome(txtNome.getText());
            b.setValor(Double.parseDouble(txtValor.getText()));
            b.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            b.setEstado(cmbEstado.getSelectedItem()+"");
            
            BebidaDAO bDAO = new BebidaDAO();
            bDAO.atualizar(b);
            
            JOptionPane.showMessageDialog(this, "Bebida " + b.getNome() + " atualizada com sucesso!", "Atualização concluída.", JOptionPane.INFORMATION_MESSAGE);
            
            limparFormulario();
        }
        else if (cmbTipoItem.getSelectedIndex() == 1){
            Comida c = new Comida();
            c.setId(Integer.parseInt(txtMostrarIDitem.getText()));
            c.setNome(txtNome.getText());
            c.setValor(Double.parseDouble(txtValor.getText()));
            c.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            c.setDescricao(txaDescricao.getText());
            c.setEstado(cmbEstado.getSelectedItem()+"");
            
            ComidaDAO cDAO = new ComidaDAO();
            cDAO.atualizar(c);
            
            JOptionPane.showMessageDialog(this, "Comida " + c.getNome() + " atualizada com sucesso!", "Atualização concluída.", JOptionPane.INFORMATION_MESSAGE);
            
            limparFormulario();
        }
        else if (cmbTipoItem.getSelectedIndex() == 2){
            Sobremesa s = new Sobremesa();
            s.setId(Integer.parseInt(txtMostrarIDitem.getText()));
            s.setNome(txtNome.getText());
            s.setValor(Double.parseDouble(txtValor.getText()));
            s.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            s.setDescricao(txaDescricao.getText());
            s.setEstado(cmbEstado.getSelectedItem()+"");
            
            SobremesaDAO sDAO = new SobremesaDAO();
            sDAO.atualizar(s);
            
            JOptionPane.showMessageDialog(this, "Sobremesa " + s.getNome() + " atualizada com sucesso!", "Atualização concluída.", JOptionPane.INFORMATION_MESSAGE);
            
            limparFormulario();
        }
        else{
        
            JOptionPane.showMessageDialog(this, "Não foi possível completar a atualização dos dados.", "Erro", JOptionPane.ERROR);
        
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void limparFormulario(){
        txtConsultaIDitem.setText("");
        txtMostrarIDitem.setText("");
        txtNome.setText("");
        txtQuantidade.setText("");
        txtValor.setText("");
        txaDescricao.setText("");
       
    }
    
    
    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void cmbTipoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoItemActionPerformed
        if (cmbTipoItem.getSelectedIndex() == 1 || cmbTipoItem.getSelectedIndex() == 2  ) {
            txaDescricao.setVisible(true);
            lblDescricao.setVisible(true);

        }
        else{
            txaDescricao.setVisible(false);
            lblDescricao.setVisible(false);

        }
    }//GEN-LAST:event_cmbTipoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConsultarItem;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipoItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMostrarID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipoItem;
    private javax.swing.JTextArea txaDescricao;
    private javax.swing.JTextField txtConsultaIDitem;
    private javax.swing.JTextField txtMostrarIDitem;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
