/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conexao;

import DAO.BebidaDAO;
import DAO.ComidaDAO;
import DAO.MesaDAO;
import DAO.PedidosDAO;
import DAO.SobremesaDAO;
import beans.Bebida;
import beans.Comida;
import beans.Mesa;
import beans.Pedido;
import beans.Sobremesa;
import java.util.List;

/**
 *
 * @author mathe
 */
public class IniciarPedidos extends javax.swing.JFrame {

    /**
     * Creates new form IniciarPedidos
     */
    public IniciarPedidos() {
        initComponents();
        preencherComboComidas();
        preencherComboBebidas();
        preencherComboSobremesas();
        preencherComboMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComidas = new javax.swing.JLabel();
        lblBebidas = new javax.swing.JLabel();
        lblSobremesas = new javax.swing.JLabel();
        cmbComidas = new javax.swing.JComboBox<>();
        cmbBebidas = new javax.swing.JComboBox<>();
        cmbSobremesas = new javax.swing.JComboBox<>();
        txtQuantidadeComida = new javax.swing.JTextField();
        lblQuantidadeComida = new javax.swing.JLabel();
        txtQuantidadeBebida = new javax.swing.JTextField();
        lblQuantidadeBebidas = new javax.swing.JLabel();
        txtQuantidadeSobremesa = new javax.swing.JTextField();
        lblQuantidadeSobremesa = new javax.swing.JLabel();
        btnVerCarrinho = new javax.swing.JButton();
        cmbMesa = new javax.swing.JComboBox<>();
        lblSuaMesa = new javax.swing.JLabel();
        btnEnviarParaCarrinho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fazer Pedidos");

        lblComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblComidas.setText("COMIDAS");

        lblBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBebidas.setText("BEBIDAS");

        lblSobremesas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSobremesas.setText("SOBREMESAS");

        cmbComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbComidasActionPerformed(evt);
            }
        });

        txtQuantidadeComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeComidaActionPerformed(evt);
            }
        });

        lblQuantidadeComida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantidadeComida.setForeground(new java.awt.Color(153, 153, 153));
        lblQuantidadeComida.setText("Quantidade");

        lblQuantidadeBebidas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantidadeBebidas.setForeground(new java.awt.Color(153, 153, 153));
        lblQuantidadeBebidas.setText("Quantidade");

        lblQuantidadeSobremesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantidadeSobremesa.setForeground(new java.awt.Color(153, 153, 153));
        lblQuantidadeSobremesa.setText("Quantidade");

        btnVerCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerCarrinho.setText("Ver Carrinho");
        btnVerCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCarrinhoActionPerformed(evt);
            }
        });

        lblSuaMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSuaMesa.setForeground(new java.awt.Color(153, 153, 153));
        lblSuaMesa.setText("MESA");

        btnEnviarParaCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnviarParaCarrinho.setText("Enviar para o Carrinho");
        btnEnviarParaCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarParaCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSuaMesa)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbSobremesas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbBebidas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSobremesas)
                                    .addComponent(lblBebidas, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(btnEnviarParaCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblComidas))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnVerCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblQuantidadeComida))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQuantidadeBebidas)
                                            .addComponent(lblQuantidadeSobremesa)))
                                    .addComponent(txtQuantidadeSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantidadeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantidadeComida, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(514, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblSuaMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblComidas)
                        .addGap(20, 20, 20)
                        .addComponent(cmbComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblBebidas)
                        .addGap(19, 19, 19)
                        .addComponent(cmbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblSobremesas)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSobremesas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblQuantidadeComida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeComida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(lblQuantidadeBebidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblQuantidadeSobremesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarParaCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 public void preencherComboComidas() {

        ComidaDAO cDAO = new ComidaDAO();
        List<Comida> listaComidas = cDAO.getComidas();
        for (Comida c : listaComidas) {
            cmbComidas.addItem(c);
        }

    }
 
  public void preencherComboBebidas() {

        BebidaDAO bDAO = new BebidaDAO();
        List<Bebida> listaBebidas = bDAO.getBebidas();
        for (Bebida b : listaBebidas) {
            cmbBebidas.addItem(b);
        }

    }
  
    public void preencherComboSobremesas() {

        SobremesaDAO sDAO = new SobremesaDAO();
        List<Sobremesa> listaSobremesas = sDAO.getSobremesas();
        for (Sobremesa s : listaSobremesas) {
            cmbSobremesas.addItem(s);
        }

    }
    
 public void preencherComboMesas() {

        MesaDAO mDAO = new MesaDAO();
        List<Mesa> listaMesas = mDAO.getMesas();
        for (Mesa m : listaMesas) {
            cmbMesa.addItem(m);
        }

    }
    
    private void cmbComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbComidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbComidasActionPerformed

    private void btnVerCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCarrinhoActionPerformed
        VisualizarCarrinho visuCarrinho = new VisualizarCarrinho();
        visuCarrinho.setVisible(true);
    }//GEN-LAST:event_btnVerCarrinhoActionPerformed

    private void txtQuantidadeComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeComidaActionPerformed

    private void btnEnviarParaCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarParaCarrinhoActionPerformed
        
            Pedido p = new Pedido();
            
            Comida comidaSelecionada = (Comida) cmbComidas.getSelectedItem();
            p.setId_comida(comidaSelecionada);
            p.setQuantidade_comida(Integer.parseInt(txtQuantidadeComida.getText()));
            p.setValor_comida(p.getId_comida().getValor());
            
            Bebida bebidaSelecionada = (Bebida) cmbBebidas.getSelectedItem();
            p.setId_bebida(bebidaSelecionada);
            p.setQuantidade_bebida(Integer.parseInt(txtQuantidadeBebida.getText()));
            p.setValor_bebida(p.getId_bebida().getValor());
            
            Sobremesa sobremesaSelecionada = (Sobremesa) cmbSobremesas.getSelectedItem();
            p.setId_sobremesa(sobremesaSelecionada);
            p.setQuantidade_sobremesa(Integer.parseInt(txtQuantidadeSobremesa.getText()));
            p.setValor_sobremesa(p.getId_sobremesa().getValor());
           
            
            Mesa mesaSelecionada = (Mesa) cmbMesa.getSelectedItem();
            p.setId_mesa(mesaSelecionada);
           
            
            
            
            PedidosDAO pDAO = new PedidosDAO();
            pDAO.inserir(p);
        
    }//GEN-LAST:event_btnEnviarParaCarrinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarParaCarrinho;
    private javax.swing.JButton btnVerCarrinho;
    private javax.swing.JComboBox<Bebida> cmbBebidas;
    private javax.swing.JComboBox<Comida> cmbComidas;
    private javax.swing.JComboBox<Mesa> cmbMesa;
    private javax.swing.JComboBox<Sobremesa> cmbSobremesas;
    private javax.swing.JLabel lblBebidas;
    private javax.swing.JLabel lblComidas;
    private javax.swing.JLabel lblQuantidadeBebidas;
    private javax.swing.JLabel lblQuantidadeComida;
    private javax.swing.JLabel lblQuantidadeSobremesa;
    private javax.swing.JLabel lblSobremesas;
    private javax.swing.JLabel lblSuaMesa;
    private javax.swing.JTextField txtQuantidadeBebida;
    private javax.swing.JTextField txtQuantidadeComida;
    private javax.swing.JTextField txtQuantidadeSobremesa;
    // End of variables declaration//GEN-END:variables
}
